version: '3.8'

services:
  # Serviço do Frontend (Nginx)
  # Este é o ponto de entrada da aplicação. Ele serve os arquivos estáticos
  # e atua como um proxy reverso para a API.
  frontend:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      # Expõe a porta 80 do Nginx para a porta 8080 da máquina host
      - "8080:80"
    # Garante que o serviço da API esteja pronto antes de iniciar o frontend
    depends_on:
      - api
    # Monta os volumes para live-reload do frontend e da config do Nginx
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  # Serviço do Backend (API FastAPI)
  # Este serviço não é exposto publicamente. O acesso é feito através do Nginx.
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Monta o código-fonte para desenvolvimento live-reload
      - .:/app
      # Monta um volume nomeado para persistir o índice FAISS
      - faiss_data:/app/faiss_index
    env_file:
      - .env
    # O comando com --reload é útil para desenvolvimento
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

# Define o volume nomeado para persistir os dados do FAISS
volumes:
  faiss_data:
    driver: local
