version: '3.8'

networks:
  rag_net:
    driver: bridge

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    environment:
      - GOOGLE_API_KEY=AIzaSyDHHi9PqeyuT7M0u-uT_DjrZ8AiyBdvnFQ
      - REDIS_URL=redis://redis:6379/0
    networks:
      - rag_net
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - rag_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
