services:
  ic-app:
    image: enzo0001/enzo-ic:v4
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ic-app.rule=Host(`ic.educia.tech`)"
        - "traefik.http.routers.ic-app.entrypoints=websecure"
        - "traefik.http.routers.ic-app.tls=true"
        - "traefik.http.routers.ic-app.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.ic-app.loadbalancer.server.port=8000"
    environment:
      - MODEL=gemini-2.5-flash
      - REDIS_URL=redis://redis:6379
      - GOOGLE_API_KEY=
      - SERPAPI_API_KEY=
      - SESS_TTL_SECONDS=28800
    networks:
      - network_public
    expose:
      - "8000"

  redis:
    image: redis:latest
    deploy:
      replicas: 1
    networks:
      - network_public
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  network_public:
    external: true
    name: network_public
